# Generated by Django 4.2.27 on 2026-01-10 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0002_alter_task_time_create'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskGroup',
        ),
    ]
